// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjghunwuwqnvhoejmsqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZ2h1bnd1d3FudmhvZWptc3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDk5NzYsImV4cCI6MjA2ODgyNTk3Nn0.xoEzq7bq1kiasG8OYAqYWhK2e106nWNEJ9A8EgKxFaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});